import { chromium } from '@playwright/test'
const out = process.argv[2]
const A = 'http://localhost/api'
const J = { Accept: 'application/json', 'Content-Type': 'application/json' }
const token = (await (await fetch(A + '/auth/login', { method: 'POST', headers: J, body: JSON.stringify({ email: 'customer@sentrypass.test', password: 'password' }) })).json()).token
const browser = await chromium.launch({ channel: 'chrome' })
const c = await browser.newContext({ viewport: { width: 1440, height: 1000 } })
await c.addInitScript((t) => localStorage.setItem('sentrypass_token', t), token)
const p = await c.newPage()
p.on('pageerror', (e) => console.log('PAGEERROR', e.message))
await p.goto('http://localhost:5175/events/5')
await p.waitForTimeout(2500)
const room = p.locator('.seatmap')
await room.scrollIntoViewIfNeeded()
await p.waitForTimeout(1500)
await p.waitForTimeout(500)
await p.screenshot({ path: `${out}/seat-room.png` })
const free = p.locator('.seat[data-free]')
console.log('free seats rendered:', await free.count())
await free.nth(12).click()
await p.waitForTimeout(700)
console.log('picked:', await p.locator('.seat[data-picked]').getAttribute('aria-label'))
console.log('caption:', await p.locator('.seatmap figcaption').innerText())
await p.screenshot({ path: `${out}/seat-picked.png` })
const btn = p.getByRole('button', { name: /Book seat/ })
console.log('book button:', await btn.first().innerText())
await btn.first().click()
await p.waitForTimeout(2500)
console.log('notice:', await p.locator('.notice').first().innerText().catch(() => 'none'))
await p.goto('http://localhost:5175/passes')
await p.waitForTimeout(2200)
console.log('badges:', await p.locator('.seat-badge').allInnerTexts())
await p.screenshot({ path: `${out}/seat-passes.png` })
await browser.close()
